### ISSUE TITLE
Update plugin model

### ISSUE THREAD

**Issue by adamschaub** [sigma-dev/sigma#97]
Update the type specification in plugin. Each plugin defines it's own types. A type consists of a base (limited to one of the primitive types) and optional constraints on allowed values.

Allowable constraints depend on the base type:
- string:
  - Regex (RE2). Values much match the regex to be allowed
  - Max/min length
  - Predefined values
- int/float:
  - Allowable ranges or enumerations

```
name: hello
summary: Sample hello plugin
description: hello Plugin
maintainer: Sigma dev team
version: v1

input:
  basic:
    type: int # allowed types: int, float, string, bool, list, object
  example-name:
    type: ip-addr
    default: 127.0.0.1
  another:
    type: chose-ten
    default: 5
  an-object:
    type: object
    body:
      field1:
        type: int
      field2:
        type: ip-addr
    default:
      field1: 0
      field2: 127.0.0.1
  typed-object:
    type: my-object
    default:
      field1: 0
      field2: 127.0.0.1
output:
  name:
    type: string
    default: Hello, world!
  some:
    type: int
    default: 0
config:
  image: sigmadev/hello


types:
  ip-addr:
    base: string
    default: 0.0.0.0
    # String constrained by a matching regex (RE2)
    regex: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$
    enum:
      - 127.0.0.1
      - 192.168.1.1
  chose-ten:
    base: int
    # Integer constrained by <,>,<=,>=,!=,==. Form of <constraint><number>.
    # Multiple constraints can be chained together using &&(and) and ||(or) (no parentheses, reduced logically)
    range: >0 && <=10
  my-object:
    base: object
    body:
      field1:
        type: int
        default: 0
      field2:
        type: ip-addr
```
